### ISSUE TITLE
Craft fields don't seem to be created after install

### ISSUE THREAD

**Issue by hannahwoodward** [FosterCommerce/shipstation-connect#11]
Under the documentation it says -

> ShipStation Connect will create a new Matrix field called "Shipping Info" under the "ShipStation Connect" Group. It will also automatically add a new tab to the Orders layout in Craft Commerce called "ShipStation Connect" which will include the Shipping Info field.

However, post-install I can't seem to see any fields that have been added to Craft.

**Comment by johnnynotsolucky** [comment]
Hi @hannahwoodward, the plugin no longer creates the fields for user. We opted to allow users to create and configure the fields themselves for a bit more flexibility and less complexity in the plugins migrations.

I've updated the documentation now: https://github.com/FosterCommerce/shipstation-connect#matrix-field.

Once you've created the field, you can configure the plugin with the new fields handles. 

Please let me know if this works for you?
