### ISSUE TITLE
The "Name" element is invalid - greater than the MaxLength value

### ISSUE THREAD

**Issue by timkelty** [FosterCommerce/shipstation-connect#14]
It appears ShipStation has a limit of 200 characters on "Name", but Craft does not, which will result in this error:

![image](https://user-images.githubusercontent.com/18329/69552648-d0ab6700-0f6c-11ea-904a-82ff40cf7e8e.jpg)

This is a Craft 2/Commerce upgrade, which may be why the names are longer (with variants?).

At any rate, seems like you should truncate to avoid this error?

**Comment by johnnynotsolucky** [comment]
@timkelty I've pushed a change with version 1.2.6 which cuts the text in the `Name` field off at 200 characters.
