### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by pioneerdesign** [FosterCommerce/shipstation-connect#17]
We setup ShipStation with our Craft Commerce site. It was working great for several days. Then it started returning 500 errors. I confirmed there were not blocking issues from our server and re-entered the ShipStation custom store username and password in Craft. When I use "Test Connection" in ShipStation it is successful. But if I try to Connect to the store it says "Failed to Update". Here is what the logs say:

```
2020-05-04 08:37:35 [-][-][-][error][fostercommerce\shipstationconnect\controllers\OrdersController::logException] Error processing action export
2020-05-04 08:37:35 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to get property 'firstName' of non-object in /home/wallpaper/craft3/vendor/fostercommerce/shipstationconnect/src/services/Xml.php:392
Stack trace:
#0 /home/wallpaper/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/wallpaper...', 392)
#1 /home/wallpaper/craft3/vendor/fostercommerce/shipstationconnect/src/services/Xml.php(392): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/home/wallpaper...', 392, Array)
#2 /home/wallpaper/craft3/vendor/fostercommerce/shipstationconnect/src/services/Xml.php(126): fostercommerce\shipstationconnect\services\Xml->shipTo(Object(SimpleXMLElement), Object(craft\commerce\elements\Order), Object(craft\commerce\models\Customer))
#3 /home/wallpaper/craft3/vendor/fostercommerce/shipstationconnect/src/services/Xml.php(39): fostercommerce\shipstationconnect\services\Xml->order(Object(SimpleXMLElement), Object(craft\commerce\elements\Order))

PHP Fatal error:  require(): Failed opening required '/home/user/craft3/vendor/composer/../league/csv/src/functions_include.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/user/craft3/vendor/composer/autoload_real.php on line 66

```

**Comment by aladrach** [comment]
Also seeing this issue popping up after working flawlessly for some time.

**Comment by pioneerdesign** [comment]
We are seeing shipping statuses being updated FROM ShipStation but sending orders TO ShipStation still results in a 500 error.

**Comment by aladrach** [comment]
> We are seeing shipping statuses being updated FROM ShipStation but sending orders TO ShipStation still results in a 500 error.

Yep, exact same here.

**Comment by sjcallender** [comment]
@pioneerdesign @aladrach - Thanks for reporting.

What versions of Craft, Commerce and ShipStation Connect are you each working with?

**Comment by aladrach** [comment]
We're on:
Craft 3.4.14
Commerce 3.0.12 (can't upgrade due to rounding issue)
ShipStation Connect 1.3.0

**Comment by pioneerdesign** [comment]
We run:
Craft CMS 3.4.17.1
Commerce 3.1.3
ShipStation 1.3.0

**Comment by johnnynotsolucky** [comment]
@pioneerdesign @aladrach This has been resolved, the fix is available in 1.3.1

**Comment by pioneerdesign** [comment]
Thank you. I ran the update, verified credentials, and attempted a connection. Got a new error this time: 
An error occurred attempting to update orders: Error in XML. Reason: The 'Value' element is invalid - The value '"._.. the message ..._ ."' is invalid according to its datatype 'String100' - The actual length is greater than the MaxLength value.

https://jmp.sh/mQKCHwF

**Comment by aladrach** [comment]
It appears to be working for us now!

**Comment by johnnynotsolucky** [comment]
@pioneerdesign it was a string length limit on the line item option values. 1.3.2 should resolve that.

**Comment by pioneerdesign** [comment]
That fixed it. Thanks!
