### ISSUE TITLE
Confirm Craft 3.5/Commerce 3.2 compatibility

### ISSUE THREAD

**Issue by timkelty** [FosterCommerce/shipstation-connect#20]
I've just upgraded a site and have had the client report that that "401 unauthorized when trying to use the URL for shipstation connect"

I haven't dug in yet, but wanted to start with an issue to see if this has been tested/confirmed on 3.5/3.2.

- Craft CMS 3.5.8
- Craft Commerce 3.2.3
- ShipStation Connect: 1.3.2

**Comment by sjcallender** [comment]
@timkelty - We'll take a look today.

**Comment by sjcallender** [comment]
@timkelty Can you share an example request to the export endpoint?

**Comment by paddling** [comment]
@sjcallender 
I am the client for this issue.  @timkelty has a crazy day today so I am hoping I can help out.
I just emailed the curl command to support@fostercommerce.com

**Comment by paddling** [comment]
FWIW - everything was working fine with the plugin up until we upgraded Craft and Commerce

**Comment by rickwiltsie** [comment]
I have a little more information on this bug. I believe it has to do with this setting in config/general.php...

'enableBasicHttpAuth' => true

It seems that Craft is intercepting the Basic Auth request and rejecting it before it reaches ShipstationConnect auth check.

**Comment by paddling** [comment]
So we found a hack as a temporary solution.  We created a user account in the CMS with the same username and password as the credentials we setup in the SS plugin settings and it works.  
Once you fix the underlying issue, we can delete that user.

**Comment by sjcallender** [comment]
Good find @rickwiltsie. Thanks for debugging.

@paddling Glad you got it working with that temporary solution. We'll take a look at this next week when @johnnynotsolucky is back from moving.

**Comment by johnnynotsolucky** [comment]
This should be resolved in [1.3.3](https://github.com/FosterCommerce/shipstation-connect/releases/tag/1.3.3).

If your site has `enableBasicHttpAuth => true` then you'll need to add a Craft user with the `shipstationconnect-processOrders` permission. That user's username and password can be used by ShipStation to access the plugins actions:

![image](https://user-images.githubusercontent.com/4161106/93083499-fc7e1180-f692-11ea-848a-fa15e40faf63.png)

Alternatively, you can disable `enableBasicHttpAuth` and keep using the original username/password in the plugins settings page.
