### ISSUE TITLE
Orders do not import properly when 'Billing address same as shipping address' disabled.

### ISSUE THREAD

**Issue by oadslug** [FosterCommerce/shipstation-connect#25]
Currently, orders do not import if the setting 'Billing address same as shipping address' is disabled and the order does not have a billing address. 

The problem is in `/services/xml.php` in the `shouldInclude()` method (line 19) when building the orders xml object.

I assumed that disabling this setting would simply leave the billing info empty, but instead it excludes the order from the orders xml. Off the top of my head, I don't know if 'billing address' is required by ShipStation or not. If not, then this should be fixed. If billing address is required, then the plugin is behaving properly, but I would recommend adding a warning in the setting description that 'Orders that do not have billing address will not be imported'.

Thanks.

**Comment by johnnynotsolucky** [comment]
@oadslug indeed customer billing information is required by ShipStation: https://help.shipstation.com/hc/en-us/articles/360025856192-Custom-Store-Development-Guide

![image](https://user-images.githubusercontent.com/4161106/106584302-b4cb2a00-654e-11eb-9bb4-98233c2c6c9c.png)

Your suggestion to include a warning label is a good one. We'll add that.

**Comment by oadslug** [comment]
Great. Thank you. I would recommend perhaps adding a note to the setting description.
