### ISSUE TITLE
Subscriptions sent to shipstation

### ISSUE THREAD

**Issue by williamhibberd** [FosterCommerce/shipstation-connect#28]
Feature Requests: It would be amazing to have the ability to send subscriptions to shipstation to help with the fulfilment of subscription-based orders.

**Comment by sjcallender** [comment]
I'm wondering if a plugin that creates Commerce orders from Commerce subscriptions would be better. We have a client site where we do this so we can manage inventory per subscription-based order.

What your use case?

**Comment by williamhibberd** [comment]
I think you are right. That would be more efficient. I wonder if that could also hook more gracefully into stock management. i.e. reduce the stock of an item that has been sold as a subscription.

Do you know of a plugin that does this?

**Comment by sjcallender** [comment]
> Do you know of a plugin that does this?

Unfortunately, not. But I know a team that would love to be commissioned to build it. 😉
