### ISSUE TITLE
Open Shipstation from Craft

### ISSUE THREAD

**Issue by RitterKnightCreative** [FosterCommerce/shipstation-connect#3]
One of our clients came from BigCommerce and is used to being able to use it within that Control Panel. I believe a Craft integration could be as simple as puling up ShipStation in an iFrame inside Craft. It would be super handy and convenient. 

Or at least give SS a menu item and link it from within the sidebar inside Craft.

![bigsup](https://user-images.githubusercontent.com/3707869/46499192-ff083900-c7e4-11e8-92c2-ae425c971a44.png)

**Comment by RitterKnightCreative** [comment]
Are you saying we can't even pull in SS into an iFrame or simply link to it from Craft?

**Comment by sjcallender** [comment]
My mistake. I tunnel visioned on the dashboard view and not the other options. Yes, we can make one of those happen.

**Comment by johnnynotsolucky** [comment]
@RitterKnightCreative 263975c9fe94a463a5d6b19eca06a3622ab56d4d Adds a link as a sub nav item in the CP menu which will take the user to the ShipStation site.

![screenshot from 2018-10-25 11-37-14](https://user-images.githubusercontent.com/4161106/47491366-fedee480-d84a-11e8-8f68-ef2eb16af347.png)
