### ISSUE TITLE
Invalid Discount price when >= $1000

### ISSUE THREAD

**Issue by dwhoban** [FosterCommerce/shipstation-connect#30]
Just received the following from Shipstation:

I understand you are running into an import error message: 
An error occurred attempting to update orders: Error in XML. Reason: The 'UnitPrice' element is invalid - The value '-1,178.65' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:float' - The string '-1,178.65' is not a valid Single value.

We are receiving this error because the unit price for one of your products is invalid. I pulled the order feed for your custom store and found the product causing this issue: 

  <SKU />
                <Name>
                    <![CDATA[TFM]]>
                </Name>
                <Quantity>1</Quantity>
                <UnitPrice>-1,178.65</UnitPrice>

**Comment by benface** [comment]
Fixed in [v1.3.6](https://github.com/FosterCommerce/shipstation-connect/releases/tag/1.3.6). Thank you reporting this!
