### ISSUE TITLE
Unable to connect to the marketplace! Error: Invalid XML

### ISSUE THREAD

**Issue by shifuma** [FosterCommerce/shipstation-connect#31]
Hi,

I'm trying to connect a marketplace in ShipStation, but when I try to test connection I get this error:

```
Store Configuration
{"Message":"Unable to connect to the marketplace! Error: Invalid XML. Error: 'Data at the root level is invalid. Line 1, position 1.' We received: '������Q(K-*��ϳU2�3P����/J\n)$���*(��qf�9*'"}
```

I selected 'Custom Store' and I'm using the custom XML page url as shown in the Settings screen: https://mysite.com/actions/shipstationconnect/orders/process

The username and password are correct (when using known-wrong credentials I get a relevant error.)

Would appreciate any help you can give!

**Comment by mupoftpr** [comment]
Checking the [ShipStation docs](https://help.shipstation.com.au/hc/en-au/articles/360024950272-Common-Store-Errors#invalid-xml-error-0-12):

> Error message: Invalid XML. Error: ''', hexadecimal value 0x1B, is an invalid character. Line [Number], position [Number].' We received: '[String]'

> This error message typically occurs during store imports because one or more orders has a carriage return in the Ship To address.

> Possible Solution:

> Check your recent orders (any orders that have not imported into ShipStation) to make sure the addresses are correct and do not contain any carriage returns. The character may not be easily visible, so you may need to edit the address on the store or marketplace to review it.

I deleted all orders to see if doing it from a blank base would work, but still get the same error.

**Comment by johnnynotsolucky** [comment]
@mupoftpr the string in the error from ShipStation looks like it _could_ be gzipped data that hasn't been decoded. But pretty hard to say for sure. It seems as though gzip encoding (if it is being used) is working correctly because you're not having an issue with Postman requests against the same endpoint.

Are you still having this issue currently?
