### ISSUE TITLE
Question: Shipping Providers/Prices

### ISSUE THREAD

**Issue by challahan** [FosterCommerce/shipstation-connect#33]
Will this plugin actually pass available shipping provider options/costs from ShipStation to the customer during checkout, or do I have to maintain those options manually in Craft Commerce? Wasn't seeing this anywhere in the features or documentation.

**Comment by sjcallender** [comment]
Good question. No, ShipStation doesn't serve as a checkout shipping options calculator. It's primarily used to manage order fulfillment (i.e., shipping labels) after orders have been placed.
I'd recommend checking out [Postie by Verbb](https://plugins.craftcms.com/postie).
