### ISSUE TITLE
Shipped Status for GLS

### ISSUE THREAD

**Issue by tadward** [FosterCommerce/shipstation-connect#34]
Craft isn't receiving the status of _Shipped_ back from ShipStation when an order uses GLS as the carrier. It gets the status update from other carriers.

Is this something with ShipStation not passing that info? If so, any suggestions on this?

Shipstation Connect v 1.3.6

**Comment by tadward** [comment]
This looks to be an issue with GLS and ShipStation and not the plugin. Orders are coming back to Craft and being marked as Shipped.

One last question, what is the delay when orders in SS are marked as Shipped to be pushed to Craft with the Shipped Status and tracking info updated?

**Comment by johnnynotsolucky** [comment]
@tadward AFAIK there isn't (much of) a delay. I think that the requests are fired as part of the flow in ShipStation. In Craft, once the request is received, the data is updated immediately.
