### ISSUE TITLE
?action=export not returning all orders

### ISSUE THREAD

**Issue by aeu** [FosterCommerce/shipstation-connect#40]
Hello, 

I'm following the instructions from here https://github.com/FosterCommerce/shipstation-connect/issues/39 to deal with addresses with no country that ShipStation is rejecting.  I created a store called standard, which only contains orders with legit addresses.  I'd like to view the output and I'm fetching orders via curl.   

From this https://github.com/FosterCommerce/shipstation-connect/issues/36#issuecomment-969914190 I should be getting all orders, but I'm only getting 25 orders.  Is there some parameter I'm missing to get all?  

Thank you,

aeu

    curl \
    --silent \
    --request GET 'https://my.domain.com/actions/shipstationconnect/orders/process?store=standard&action=export' \
    --header 'Authorization: Basic 9s7df987sdf98adfklasklfjkalsdf='

    ./production_shipstation_curl.sh | tidy -xml -iq | grep OrderID | wc
    line 2 column 29459 - Warning: replacing invalid character code 133
    line 2 column 29870 - Warning: replacing invalid character code 133
          25      25     725

**Comment by sjcallender** [comment]
You might need to update (via resaving) all orders so their dateUpdated falls within the range ShipStation is expecting.

**Comment by sjcallender** [comment]
`action=export` only includes orders within the date range that ShipStation attaches to the endpoint when it fetches the data. It'll process orders across multiple pages in the same request too.

From the [ShipStation custom store docs](https://help.shipstation.com.au/hc/en-au/articles/360025241611-Custom-Store-Development-Guide#get-call-0-4):

> Your page should return data for any order that was modified between the start and end date, regardless of the order's status.

**Comment by aeu** [comment]
Hi @sjcallender - I'm using curl, no date at all (see above).

**Comment by sjcallender** [comment]
Sorry. I forgot the context. I guess I don't understand the issue. If you set the Page Size for Orders to higher count (more than your actual order count) do you see them all?

**Comment by sjcallender** [comment]
Also, you can use the `page` parameter to see more than page 1.

ex: `?action=export&page=3`
