### ISSUE TITLE
Exported orders should respect XML Schema for Validating Order Information

### ISSUE THREAD

**Issue by jlachancekffein** [FosterCommerce/shipstation-connect#41]
We had an issue with an order containing a value for the Company field that was too long.

This issue is with the export orders endpoint : actions/shipstationconnect/orders/process?action=export

According to the Shipstation documentation, this field has a maximum of 100 characters.

https://help.shipstation.com/hc/en-us/articles/360025856192-Custom-Store-Development-Guide#UUID-1bb7ab47-6cf4-c6cd-0e5b-dec61e91201b_UUID-738eed11-ec21-be53-efb4-5fadcdde7b0f

I think it would be interesting for the plugin to manage the value of the fields to respect the documentation.

Otherwise, we have no choice but to manage field value on our side.

**Comment by johnnynotsolucky** [comment]
This will be possible now that #61 is done.
