### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by bboy-splendid** [FosterCommerce/shipstation-connect#45]
Any news on an update for Craft 4?

**Comment by sjcallender** [comment]
Hi @bboy-splendid - We're waiting on this fix from the Craft team: https://github.com/craftcms/cms/issues/11435#issuecomment-1157005154

**Comment by bboy-splendid** [comment]
Looks like that was fixed a couple weeks ago - any use?

**Comment by bboy-splendid** [comment]
@fantasticmachine Many thanks for the update. We are just awaiting this and one other plugin to be able to upgrade our project to Craft 4 so would be happy to trial this when we are fully ready to upgrade!

**Comment by fantasticmachine** [comment]
@bboy-splendid If you want to give it a whirl then you can install from the `developcraft4` branch by setting your composer requirement to 

`"fostercommerce/shipstationconnect" : "dev-developcraft4"`

Seems like it's retrieving orders from Commerce OK but so far I've been unable to confirm that the shipping info is fed back to Commerce.

**Comment by fantasticmachine** [comment]
@bboy-splendid I've managed to do some more testing and can confirm the plugin appears to be working correctly in Craft 4.
Orders are being captured and sent to Shipstation and, in turn, are updated within Commerce when Shipstation marks them as shipped.

**Comment by fantasticmachine** [comment]
The Craft 4 compatible version is now officially released
