### ISSUE TITLE
error when refreshing feed from shipstation

### ISSUE THREAD

**Issue by samuelbirch** [FosterCommerce/shipstation-connect#5]
Hi,

I'm getting this error when try to refresh the feed from shipstation:

```
Error processing action export
DOMDocument::createCDATASection() expects parameter 1 to be string, array given in /vendor/fostercommerce/shipstationconnect/src/services/Xml.php:500
```

is it possible to check if its an array and if it then json_encode it perhaps?

```
    protected function addChildWithCDATA(&$xml, $name, $value)
    {
        $new_child = $xml->addChild($name);
        if ($new_child !== null) {
            $node = dom_import_simplexml($new_child);
            $node->appendChild($node->ownerDocument->createCDATASection(json_encode($value));
        }
        return $new_child;
    }
```

Craft Pro 3.1.30
Commerce: 2.1.7

**Comment by samuelbirch** [comment]
encoding the value doesn't help, it just throws other errors.

Has something in commerce changed that is causing the plugin to no longer work?

**Comment by sjcallender** [comment]
@samuelbirch What versions of Craft and Commerce are you using?

**Comment by samuelbirch** [comment]
Craft Pro 3.1.30
Commerce: 2.1.7

**Comment by samuelbirch** [comment]
just updated to commerce: 2.1.9 - still have the same issue

**Comment by samuelbirch** [comment]
if i set it up in a staging environment it seems to work, just not in a production environment

**Comment by samuelbirch** [comment]
finally got to the bottom of it. - i've done a pull request that fixes the issue.
