### ISSUE TITLE
FR: ability to set phone for addresses

### ISSUE THREAD

**Issue by jmauzyk** [FosterCommerce/shipstation-connect#51]
Since upgrading to Commerce 4, phone numbers are no longer automatically mapped for addresses since they were removed from the Address model. Would be nice to add a feature to set phone numbers again, either through a plugin setting allowing admins to set the field handle for phone numbers or through an `OrderFieldEvent`.

**Comment by johnnynotsolucky** [comment]
@jmauzyk this should be resolved now in v2.0.3.
