### ISSUE TITLE
No shipping info coming through shipstation connect.

### ISSUE THREAD

**Issue by booyaamps** [FosterCommerce/shipstation-connect#53]
Hello!
  Craft 4.5 site with newest craft commerce.
Using Postie for shipping rates, which is working well (orders are able to get real time shipping rates, and the orders show up with the correct shipping in craft. see below.)
![image](https://github.com/FosterCommerce/shipstation-connect/assets/45020893/78ba9405-ea1b-4f3a-979a-29f9be8d3a12)

None of that shipping info is coming into the order in shipstation, though- the service, package type, or anything else. When i ping the Shipstation Connect XML URL through postman, the ShippingMethod block is blank. Searching the XML output for the purchased shipping method (i.e. CTRL-F, "fedex") returns no results.

       <ShippingMethod>
            <![CDATA[]]>
        </ShippingMethod>

Is this behavior expected?

**Comment by johnnynotsolucky** [comment]
Hi @booyaamps, this is not expected behavior. I'm unfamiliar with Postie, to clarify, the shipping methods you have configured are configured by that plugin and _not_ from Commerce -> Shipping -> Shipping Methods?

**Comment by booyaamps** [comment]
Correct! Rates come from Postie and not Commerce->Shipping->Shipping Methods.

**Comment by johnnynotsolucky** [comment]
@booyaamps the issue should now be resolved in v2.0.2 with #54 

Please give us a shout if this doesn't solve the problem for you.

**Comment by booyaamps** [comment]
You rock. Seriously, thank you so much.
        <ShippingMethod>
            <![CDATA[FEDEX_GROUND]]>
        </ShippingMethod>
Works like a charm!
