### ISSUE TITLE
Craft 5 Compatibility

### ISSUE THREAD

**Issue by StewardOF** [FosterCommerce/shipstation-connect#60]
Please could you advise as to when ShipStation (third party plug in) will be available and compatible for use on Craft 5 Commerce / Ecommerce platform?

**Comment by johnnynotsolucky** [comment]
Hi @StewardOF, we're planning to upgrade ShipStation Connect in the coming months. We'll keep this issue updated once we start work on it.

**Comment by StewardOF** [comment]
Thank you - please could you keep us updated with the progress and timelines for this work starting / being completed.

**Comment by StewardOF** [comment]
Thank you for the below.

Please keep us updated as to when these works begin and any timelines available to share in terms of completion of upgrades and testing, in order for this to be compatible on site.

Many thanks
Emily


Emily Steward
PR & Marketing Coordinator
Overfinch
151 - 153 Park Road
​St John's Wood
​London
​NW8 7HT
T: 0207 4166 199
E: ***@***.***
www.overfinch.com
Overfinch Limited, a limited company incorporated in England and Wales with registration number 03341094 and with a registered office at 151-153 Park Rd, St John's Wood, London, NW8 7HT.  
Overfinch Limited (FCA No.:664513) and / or Overfinch Finance Limited (FCA No.: 661915) are authorised by the Financial Conduct Authority. Overfinch is a credit broker and not a lender.
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by StewardOF** [comment]
Hi,

Is there any further update on the Ship Station being made available for Craft 5?

Please let me know.

Many thanks
Emily


Emily Steward
PR & Marketing Coordinator
Overfinch
151 - 153 Park Road
​St John's Wood
​London
​NW8 7HT
T: 0207 4166 199
E: ***@***.***
www.overfinch.com
Overfinch Limited, a limited company incorporated in England and Wales with registration number 03341094 and with a registered office at 151-153 Park Rd, St John's Wood, London, NW8 7HT.  
Overfinch Limited (FCA No.:664513) and / or Overfinch Finance Limited (FCA No.: 661915) are authorised by the Financial Conduct Authority. Overfinch is a credit broker and not a lender.
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
From: Emily Steward
Sent: Wednesday, May 15, 2024 3:49 PM
To: FosterCommerce/shipstation-connect ***@***.***>; FosterCommerce/shipstation-connect ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [FosterCommerce/shipstation-connect] Craft 5 Compatibility (Issue #60)

Thank you for the below.

Please keep us updated as to when these works begin and any timelines available to share in terms of completion of upgrades and testing, in order for this to be compatible on site.

Many thanks
Emily

**Comment by StewardOF** [comment]
Hi - has there been any further developments with Ship Station being made available for Craft 5 commerce? Many thanks

**Comment by johnnynotsolucky** [comment]
@StewardOF we're still looking to schedule this upgrade in the next month or two.

Please feel free to contact us directly at support@fostercommerce.com as well!

**Comment by StewardOF** [comment]
Hi,

I hope you're well.

Please could you advise as to whether there has been any further updates on the compatibility with craft 5?

Many thanks,
Emily


Emily Steward
Marketing and Brand Communications Manager
Overfinch
151 - 153 Park Road
​St John's Wood
​London
​NW8 7HT
T: 0207 4166 199
E: ***@***.***
www.overfinch.com
Overfinch Limited, a limited company incorporated in England and Wales with registration number 03341094 and with a registered office at 151-153 Park Rd, St John's Wood, London, NW8 7HT.  
Overfinch Limited (FCA No.:664513) and / or Overfinch Finance Limited (FCA No.: 661915) are authorised by the Financial Conduct Authority. Overfinch is a credit broker and not a lender.
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by peteeveleigh** [comment]
Hi @StewardOF 
Sorry for the delay in replying. @johnnynotsolucky is on leave at the moment and I don't have an answer to your question to hand as I'm not working on this project right now.  But I'll get an update for you asap.

**Comment by peteeveleigh** [comment]
@StewardOF 
I'm afraid we still don't have the Craft 5 version ready for release. We are undertaking a refactor of the XML generation logic and, unfortunately, we have had to park it while we get some other plugins ready for Craft 5.

Hopefully, we will be back on this in the next month and get a release out.

**Comment by terryupton** [comment]
Thanks @peteeveleigh - will you be able to give an updated when this is back in the pipeline and are we looking at a possible release before the end of the year? Thanks.

**Comment by sjcallender** [comment]
As an update, we've begun this work and have the bulk of the plugin ready. We've been taking this opportunity to refactor, especially how the XML is created. That work is done. We're chipping away now at some final bits. It's looking like we'll be able to have the Craft 5 release this month. 🤞

**Comment by johnnynotsolucky** [comment]
@StewardOF @terryupton we have published https://github.com/FosterCommerce/shipstation-connect/releases/tag/3.0.0-beta.1, which is ShipStation Connect's Craft 5 update.

Please give it a go and let us know if there are issues. Also please take note of the changes in the CHANGELOG, especially if you are using Custom Fields. The functionality has [changed](https://github.com/FosterCommerce/shipstation-connect/issues/22#issuecomment-2456336829).

**Comment by johnnynotsolucky** [comment]
We have published https://github.com/FosterCommerce/shipstation-connect/releases/tag/3.0.0.
