### ISSUE TITLE
Shipping Method Name

### ISSUE THREAD

**Issue by jmauzyk** [FosterCommerce/shipstation-connect#7]
I'm wondering if it would make sense to use the shipping method name instead of its handle when sent to ShipStation. The Craft 2 ShipStation plugin had a hook that allowed plugins to override the text sent to ShipStation, but since hooks have mostly been done away with in Craft 3, I don't think this is possible. As far as I can tell, the shipping method is only used by ShipStation to display what method was requested when preparing a shipment. In that case, would it make sense to use a more human readable format and send `$shippingMethod->name` instead?

**Comment by johnnynotsolucky** [comment]
Hi @jmauzyk, we can use events to do something similar to what hooks did. I’ll have a look at adding back functionality to customize the shipping method.

**Comment by jmauzyk** [comment]
@johnnynotsolucky Sounds good, thanks for looking into it!

**Comment by johnnynotsolucky** [comment]
@jmauzyk I've published [1.1.0](https://github.com/FosterCommerce/shipstation-connect/releases/tag/1.1.0) which includes events for some extra fields and also lets you choose to override the OrderNumber and ShippingMethod defaults.

For ShippingMethod you can do something like this:

```php
Event::on(
    Xml::class,
    Xml::ORDER_FIELD_EVENT,
    function (OrderFieldEvent $e) {
        $fieldName = $e->field;
        $order = $e->order;

        if ($fieldName === OrderFieldEvent::FIELD_SHIPPING_METHOD) {
            $e->data = "My Shipping Method";
        }
    }
);
```

**Comment by johnnynotsolucky** [comment]
I've published a new release, [1.2.0](https://github.com/FosterCommerce/shipstation-connect/releases/tag/1.2.0), which changes the `data` event property to `value` since the event's parent class already defines a data property.

```php
Event::on(
    Xml::class,
    Xml::ORDER_FIELD_EVENT,
    function (OrderFieldEvent $e) {
        $fieldName = $e->field;
        $order = $e->order;

        if ($fieldName === OrderFieldEvent::FIELD_SHIPPING_METHOD) {
            $e->value = "My Shipping Method";
        }
    }
);
```

**Comment by jmauzyk** [comment]
Thanks again!

**Comment by chadcrowell** [comment]
Could you *please* update the read me with the $e->value change? I just spent 2 hours placing test orders trying to figure out why Craft won't pass note and custom field data to SS using $e->data. For others' sake.
