### ISSUE TITLE
Stringy Naming Collision

### ISSUE THREAD

**Issue by jmauzyk** [FosterCommerce/shipstation-connect#8]
Just installed Craft 3.3 and was starting to test it when I ran into a naming collision issue with Stringy. Craft 3.3 switches from `danielstjules/Stringy` to `voku/Stringy`. This wouldn't be an issue except that Craft 3.3 now uses the `snakeize()` method (unique to voku) for the `|snake` twig filter. Because composer defaults to the old `danielstjules/Stringy` when generating autoload files, I now get a call to undefined method error when using the snake filter. Can you switch from the danielstjules version to the voku version to avoid this collision?

**Comment by jmauzyk** [comment]
Dug into this a bit more, looks like it is specifically the composer.lock file that has a reference to `Stringy` and is causing issues.

**Comment by sjcallender** [comment]
@jmauzyk We haven't tested this with Craft 3.3 yet.

**Comment by johnnynotsolucky** [comment]
We shouldn’t be including the lock file in the plugin. composer.json is sufficient. I’ll update.

**Comment by jmauzyk** [comment]
Thanks, guys!

**Comment by johnnynotsolucky** [comment]
@jmauzyk this should be resolved in [v1.2.2](https://github.com/FosterCommerce/shipstation-connect/tree/1.2.2). Let me know if this works, and I'll close this issue.
