### ISSUE TITLE
The remote server returned an error: (404)

### ISSUE THREAD

**Issue by robdove** [FosterCommerce/shipstation-connect#9]
I'm always getting 404 errors when connecting or updating from ShipStation. When I check the server logs it's accessing the correct URLs.  It's not liking the authentication for some reason.

Is there any particulars that need configuring on the server to work?

**Comment by johnnynotsolucky** [comment]
@robdove if you've set the username/password in the ShipStation Connect plugin settings to `username` and `password`, you should be able to test the URLs with this:

```bash
curl -X GET \
  'https://yoursite.com/actions/shipstationconnect/orders/process?action=export' \
  -H 'Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ='
```

Or, if you have stores setup:
```bash
curl -X GET \
  'https://yoursite.com/actions/shipstationconnect/orders/process?store=yourStoreA&action=export' \
  -H 'Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ='

curl -X GET \
  'https://yoursite.com/actions/shipstationconnect/orders/process?store=yourStoreB&action=export' \
  -H 'Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ='
```

**Comment by robdove** [comment]
I've had to add this to my apache config and now the authentication works

`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`
